In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent = ['the glass of milk', 'the glass of juice', 'the cup of tea', 'I am a good boy', 'I am a good developer', 'understand the meaning of words', 'your videos are good']

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define vocabulary size
voc_size = 1000

one_hot_repr = [one_hot(words, voc_size)for words in sent]


In [5]:
one_hot_repr

[[966, 262, 693, 589],
 [966, 262, 693, 493],
 [966, 73, 693, 630],
 [363, 762, 101, 752, 529],
 [363, 762, 101, 752, 866],
 [635, 966, 193, 693, 253],
 [412, 295, 113, 752]]

In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 966 262 693 589]
 [  0   0   0   0 966 262 693 493]
 [  0   0   0   0 966  73 693 630]
 [  0   0   0 363 762 101 752 529]
 [  0   0   0 363 762 101 752 866]
 [  0   0   0 635 966 193 693 253]
 [  0   0   0   0 412 295 113 752]]
